### PR TITLE
Fix OpenSSL cross-compilation error

### PR DESCRIPTION
**Pull request by Selyatin**
Just enabled the OpenSSL's "vendored" feature, which fixes cross-compilation errors related to it.

You can refer [this](https://lib.rs/crates/openssl) and search for "Vendored".

Also added **objc** dependency for **OSX** builds, which will be used to interface with the Objective-C runtime and thus Apple's AppKit APIs.

### CODE REVIEW

**Comment by phiresky** [comment]
that makes sense, but did you verify whether this improves the situation on windows and does not worsen it on linux? on linux you usually want to link against system libraries and openssl is almost always present, using the vendored version might cause other issues

**Comment by Selyatin** [comment]
I've tested it on Arch Linux and it hasn't caused any issues, I've also used the **vendored** feature a lot before and it never caused any issues, but it might make sense to enable the **vendored** feature only for Windows, since on Linux OpenSSL is generally available as a dynamic library. What do you think?

**Comment by phiresky** [comment]
I think ideally it should be to default to vendored only on windows, but have an `openssl_vendored` feature in timetrackrs that enables vendored for openssl on all platforms

**Comment by phiresky** [comment]
Thinking about it again, just make it an optional feature in the first place instead of detecting the OS - since on windows it also works without vendored if you have vcpkg etc set up correctly. Just add it to the readme for windows.

**Pull request merged**
